export const NODE_WIDTH  = { hub: 148, branch: 190 };
export const NODE_HEIGHT = { hub: 108, branch: 84 };

export const INITIAL_NODES = [
  {
    id: 'hub',
    type: 'hub',
    position: { x: 46, y: -54 },
    data: { label: 'BEMON', sublabel: '팀 컨트롤 타워' },
    width:  NODE_WIDTH.hub,
    height: NODE_HEIGHT.hub,
  },
  {
    id: 'projects',
    type: 'branch',
    position: { x: -400, y: -155 },
    data: { label: '프로젝트', emoji: '📂', accent: 'salmon',  parentId: 'hub', side: 'left',  hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'schedule',
    type: 'branch',
    position: { x: 430, y: -250 },
    data: { label: '베몽 달력', emoji: '📅', accent: 'sky', parentId: 'hub', side: 'right', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'brainstorm',
    type: 'branch',
    position: { x: -400, y: 71 },
    data: { label: '브레인스토밍', emoji: '💡', accent: 'green', parentId: 'hub', side: 'left', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'compass',
    type: 'branch',
    position: { x: 430, y: -80 },
    data: { label: 'BEMON 나침반', emoji: '🧭', accent: 'violet', parentId: 'hub', side: 'right', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'goals',
    type: 'branch',
    position: { x: -160, y: 300 },
    data: { label: '이달의 퀘스트', emoji: '🎯', accent: 'mustard', parentId: 'hub', side: 'left', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'completed',
    type: 'branch',
    position: { x: -400, y: -300 },
    data: { label: '프로젝트 완수!', emoji: '🏆', accent: 'emerald', parentId: 'hub', side: 'left', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'thankyou',
    type: 'branch',
    position: { x: 430, y: 450 },
    data: { label: '땡큐 베리 머치', emoji: '🙏', accent: 'coral', parentId: 'hub', side: 'right', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
  {
    id: 'ideabank',
    type: 'branch',
    position: { x: 280, y: -420 },
    data: { label: '이건 대박!', emoji: '💡', accent: 'hotpink', parentId: 'hub', side: 'right', hasChildren: false },
    width:  NODE_WIDTH.branch,
    height: NODE_HEIGHT.branch,
    hidden: true,
  },
];

export const INITIAL_EDGES = [
  { id: 'e-hub-projects',   source: 'hub', target: 'projects',   type: 'rough', data: { color: '#C06850', seed: 1 } },
  { id: 'e-hub-schedule',   source: 'hub', target: 'schedule',   type: 'rough', data: { color: '#0284C7', seed: 2 } },
  { id: 'e-hub-brainstorm', source: 'hub', target: 'brainstorm', type: 'rough', data: { color: '#6B7C5C', seed: 3 } },
  { id: 'e-hub-compass',    source: 'hub', target: 'compass',    type: 'rough', data: { color: '#7C3AED', seed: 5 } },
  { id: 'e-hub-goals',      source: 'hub', target: 'goals',      type: 'rough', data: { color: '#D4A843', seed: 4 } },
  { id: 'e-hub-completed',  source: 'hub', target: 'completed',  type: 'rough', data: { color: '#388E3C', seed: 6 } },
  { id: 'e-hub-thankyou',  source: 'hub', target: 'thankyou',  type: 'rough', data: { color: '#E8896A', seed: 7 } },
];
